---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-ss-dev
  namespace: dev
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgDLTIyAxhzZi5cQuozZEXuJMDYNZVVU0V3q4PgGuZQxoxYxe9s+LO4oSzn/6UOGZDW+dHP3ebX6Y9ws3owSl4sR2GaM8Ax/NlloiHgd0OGXc2RnGZqneZfZqlXZ30JcH6jq78kI9my5n232sn31nWuupTVhfEwiPhUELizPQ2nfgntTLPcvbpSwSaW4gIJKYwdd3HH3lrOZusKoHCZh7/zN/Q6022ZakXEeGwZAD6UUVLfbjikYZQX1f9m1qsCDB834lXkTX8aSz/+z5jkcg5M2GosCkPyEIK49iWtx2HXLWSRwejC5qunWjtOaCvLhoQiD4p5paF54dQwVWPCdu6vk01/Wczj+qqf1Nd3DoH/TzGECNlzJlL79UovRD3PaalALb88A5OYGAl0LX0AIYMM6h7Vw3EBkFbJyOzKdzhxLRiCc/FHpclfZHWCUcCwxG6AbR2vvDu7ZW1j6UyPyL+4UdZWmTMp6WmG7j1tQZvqkI4ih3TlKvyIxdxkQh2iYsWmM2nYZrkVv2llsPdNAZrdSlV5kndZtENfS9bu1FxoGoJzxrfxsAtpR+cltEuRaiwTzttvsBiDwI22WdYFx3lsGlJaX6HvawONq58LpYfanGy4anqKHZZb0gvpoeT9FnBPF9TaQa0YcQujiF7ol0l45IgcyI4xfcZaxnkh0h5/Xo2jtL9VD6jpAJAPAd9wzA88xrBRSf8EpjYU=
    KEYCLOAK_ADMIN_PASSWORD: AgC72VeR9zQ9iBNdlQ2Uci5qhtNhdZAggnbVdSSSwA2DpAXRkeb51rdhQ/9mHWXOhYbAhKpMVkTBz54NW+aI5SpB7t4UJ05RYe7GROD2E9w6Xq+Mflnt0qEX+U990oQCsL+HgTkq2fo1/1OdyWl8O4hO1J8sDoHls0GSVn6OE8muLTx8wQdcrNmHs6NKE34FlVlOhmubuXy+IGq53xOMw1HfqHCru/F96M8B1t25I3+epp98KdKcpG2Y6hoCpQW+Sp9lO637f4v5yHeuTFoLpuUJwFZk4fDjNDMDIqi0byTaBb+VBhW6G8vNqqbQijc+e1fWkEKSmpSOkJmhcYO4mvms1s4yaCYroi3Jdu3iy2bfAfZHh0fl8UVwcn3UkD5GIyg302jO67LpGEdfmp576jNepmgdtTeJGR+V5hj7s+eJAPt9iCjxV5Ja1a8hEeQhHiXyYX8OzTv39f9AafYZegtX6NMadvfKLiJ//gmPd8MfO7evLLKRGrCqYLIPVczGkB5ND8icGEtdMut/RYdVp+PzFRUyIWQ2LhfaCxXsRaxbe+764pJsWemZDvIay3Br3+e1x58F4nAqG8N2xneFs90cEC4aZUUsS5ZbgZaTbwsCo0QFYyQglg9d2zZ3H6Co7is6YMlplsaFA/1NuJFIY4vNgsKfos53ieyHdpDdXJw0cORyj7jMZ0xrw4kg9IAy+dRhpXRqN9RDAPpRMObO
  template:
    metadata:
      name: keycloak-ss-dev
      namespace: dev
