apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}

spec:
  encryptedData:
    POSTGRES_PASSWORD: {{ .Values.secret.encryptedData.POSTGRES_PASSWORD }}
    REPLICATION_PASSWORD: {{ .Values.secret.encryptedData.REPLICATION_PASSWORD }}

  template:
    metadata:
      name: {{ .Values.secret.name }}
      namespace: {{ .Values.namespace }}

    type: Opaque