apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: dev
spec:
  encryptedData:
    password: AgCUSTQLI1T/QStebcZBDBRYdFA8XPn7tvRTZJcXgTDtsR2QN87AFdKHq4E0GdsRkLulxKMuNl6jUWoWzAgWBegL+RVemWNLidQOJilZRcyLMKEnjWC2D/2nhJ4XWyyqUerW2g46dvQ+Idj1g2GmuUgqce8WIC6dmVht8zQZjyJa7r/Pvo9wX98ozSgHHqB65OXW0IvcpGVEihLGk2ApRWZqBsRLefuCklDEbkEiaYiPo673+wzG9eLRWrCBctto+2zJcyHu/LL1/o4T0CshK783+gXgqsTuz+FPS32CcpQGD9fFyHG+5zp4n6hU0Xa5K04EflIaGEPOTgrG25egR7+yPl/+Oncyf9nA9wCNaMUJQtSRCDL/Uibhzcd+siscSqVmYPm/eCk1xA7NsShRA/E4T5rR0BhQlcjYDqBy/jrl58KaYyOYXxYeftrk3orKS6j6dymyyWoXujtTKc2R/1Z5m+yGLKjRW1F6i5VPMouOfVCSGC0Q++3m6gbIrznXjvjuYJTrXVAA4D7r7b9Pa0QUnV6TQAor1G8P5lsD44UyOHTIegPK9MhfifUvuFfGwekdm1QzzZFGJBX6fGgR1uWBTey26ttlgK00F0Y7eI3B93fI+Lp+oAgF1eBrTFPTnKVpa8ym8bWSHejAxXR8TXIcZ3doPFWRm0MiDcgugvZNYRf8ilcyi7Cue49OMh+9RsYmaZ0VBA==
    username: AgAifrvzxaR5ajRdXXkdXGP2mTONf1hSXDE6hcnlqqK1byAPZg0EFa3j/XN7QQWsOZLPyKoDjbFMu8oanH0vISicxkGBhMQ/jSebyKDSuz3sduoxgVLKSQBslyGk3Vmy+u10tRfsVYANLeAdYH0Fq5L7e/GxfA+eJhkffe0bZJGBkNX635KMwt9DCnZXyq1HiBOoziDTcz4MM3BrUTVuauTc5aUfTJaHCLsyJXyTIu3fgOAtWQ+fEYVzgL3b4+txColb2ozrbeTnRE8xsxE9cF7lJ0LN0HIk6bUxfqL1smbkWXzua2Dd63ayyLqN/DQ/AszNnMe8kISjYUo+p1H9un4rfsas7od7eEoRul94NFy/BcpybVBXv2fzvE0ZTcpnXuSys773fUbDF3qAJfxPIAxxMV8Kub4IAvQmXpqv3tez8rZvz2pIkXTzXaORF0o/32lcvmvkVheb0o9jj3UNjhax0vvbMDX2S7g1KVYGwDeCqs80ofm84nBz9MLCqqI18K/SkghXUqmglNAeX9YRTOQcOcvsEDvsaj26e9NtsUWJZ8J1sOZueCLScCbedtc0HA+ul4dW/7HN+HfnJIodhvgfKg7pAps9+EVQMnvoN6Q9JWNLiyWggZHsGh/6cMy9d1WlEI847oK0AVnSyo+A/VnlwXt2pwXHlYqCshpIlozuvTZrz59D1IDYw/9QKjcXhcGMEews
  template:
    metadata:
      name: mysecret
      namespace: dev
